spring:
  application.name: eureka-server
  profiles.active: dev
logging:
  level:
    root: INFO
  file: ${spring.application.name}.log

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/javascript,text/css,text/xml,text/plain
    min-response-size: 2048
  tomcat:
    accept-count: 400
    uri-encoding: utf-8
    min-spare-threads: 25
    max-threads: 400
    connection-timeout: 20000

spring.cloud.client.ipAddress: 127.0.0.1
eureka: 
    environment: ${spring.profiles.active}
    instance:
        hostname: localhost
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    client:
        registerWithEureka: true
        fetchRegistry: true
    server: 
        waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
        
---  
spring:
  profiles: dev
server:
    port: 7000
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:7000/eureka
